### ISSUE TITLE
RuntimeError: Unrecognized or unsupported scheme: "".

### ISSUE THREAD

**Issue by NeonN3mesis** [AutoPackAI/beebot#8]
I'm running in ubuntu via wsl2 in windows 11. Not sure if this is a supported environment.

```*****@NeonNemesis:~/beebot$ poetry run beebot
What would you like me to do?
> get the css styling information from https://www.flaotplane.com
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/*****/beebot/beebot/initiator/cli.py", line 35, in main
    initialize_db(config.database_url)
  File "/home/*****/beebot/beebot/models/database_models.py", line 88, in initialize_db
    database = connect(db_url)
  File "/home/*****/.cache/pypoetry/virtualenvs/beebot-gxFpor5K-py3.10/lib/python3.10/site-packages/playhouse/db_url.py", line 102, in connect
    raise RuntimeError('Unrecognized or unsupported scheme: "%s".' %
RuntimeError: Unrecognized or unsupported scheme: "".

**Comment by erik-megarad** [comment]
This should be fixed now. Make sure the `DATABASE_URL` value in .env is set to `DATABASE_URL=sqlite://:memory:` or a `postgresql://` URL.
